" Default shit
set nocompatible
filetype off

" Include Vundle
set rtp+=~/.vim/bundle/Vundle.vim

" Plugins
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'Shougo/neocomplete.vim'
Plugin 'tomtom/tlib_vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'bling/vim-airline'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/syntastic'
Plugin 'edkolev/promptline.vim'
Plugin 'edkolev/tmuxline.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
Plugin 'Raimondi/delimitMate'
Plugin 'airblade/vim-gitgutter'
call vundle#end()
filetype plugin indent on

" Plugin Specific options
" Neocomplete options
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 4
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'
" Tab completion
inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
if !exists('g:neocomplete#sources#omni#input_patterns')
	let g:neocomplete#sources#omni#input_patters = {}
endif

" GitGutter
highlight clear SignColumn

" Airline
let g:airline_powerline_fonts = 1
let g:airline#extension#tabline#enabled = 1
let g:airline#extensions#hunks#enabled = 1
set laststatus=2

" DelimitMate
let delimitMate_autoclose = 0

" My options
set langmenu=en_US.UTF-8
let $LANG = 'en'
set autoindent
set rnu
set nu
set hidden
syntax on
set ignorecase
set smartcase
set hls
set lbr
set encoding=utf-8
set foldmethod=marker
" Colorscheme
colorscheme smyck
" Change tab to four spaces
set tabstop=4
set shiftwidth=4
set expandtab
" Visual bell and cursorline
set visualbell
set cursorline
" Leader
let mapleader = ","
" other stuff
set showmode
set backup
set backupdir=~/.vimbackups
set dir=~/.vimbackups

" Windows only
set guifont:Sauce_Code_Powerline:h10:cANSI

" Get rid of gross gui shit
set guioptions-=m
set guioptions-=T
set guioptions-=r


" Custom mappings
noremap <F9> :e ~/.vimrc<CR>
noremap <F6> :so ~/.vimrc<CR>
noremap <C-s> :w <CR>
noremap <Leader>l :bnext<CR>
noremap <Leader>h :bprev<CR>
noremap <Leader>w :%s/\s\+$//<CR>

nnoremap ; :

