* Mon Sep  8 14:07:49 2014
** The Dead
*** Gabriel and Lily
Gabriel offers Lily a tip.
This gives Gabriel anxiety because he had been so inappropriate regarding her marriage.

*** Types of conflict
Generational conflict, male female conflict
Men continue to feel dominant, and women are beginning to assert themselves.

*** Gabriel's anxiety
Gabriel doubts himself. He doesn't want to come off as pretentious, even though he feels better than everyone else.

*** Julia
Julia is going into dementia.

*** Gabriel's hubris
Gabriel is very insecure, he doesn't want to come off as better than everyone, but still wants to be the center of attention.

*** Gabriel and Gretta
Gretta stops in her tracks after hearing the song.

Gabriel sees his wife at the top of the stairs and his filled with desire, and he is hoping that when they get home only good things will happen.
When they get back, he looks at her, asks what's wrong, and he recounts a story of a debt.
He thinks that she's thinking what he's thinking, until she runs on to the bed crying.
He essentially forces from her the story of the song. She remembered a young man, whom she feels died for her. Michael Furey
They had been in love. He got sick and died, which she has carried all these years with her.
She feels guilt because somebody else died for her.

This is not what Gabriel needed.

Gabriel goes over to the window and he watches the snow fall. "The snow is the great equalizer, falling on both the dead and living."

A symbol of how everything going on in Ireland is determined by the past. It's frozen, nothing is changing.

*** Why is the title "The Dead"?
Joyce was villified in a number of corners, as people viewed it as an utter indictment and stagnation in Ireland.
He said "No, the people in this story are just friends."
Humanity is not necessarily about the big things, it's about getting together with people with you may or may not know for music and dancing.
All of the guests wre there with there own unique niche.
* Tue Sep  9 08:31:48 2014
** The Dead Continued
*** What is the importance of the snow being the worst in 30 years?
It is universal, blanketing the entire island.

*** What is the significance of him wanting to go west?
Miss Ivors suggests that he travels West. The idea is that the west is the heart of the true Ireland.

*** What's the significance of Freddy Malins?
Freddy is just another character with unique characteristics.

*** Is he in favour of going back to a more traditional Ireland?
Joyce himself was very conflicted about that. He was very proud of his heritage, but hated all of the stereotypes and trappings that brought with it. He married a girl very much like Lily.
He lived with a woman who had been a housemaid, named Norah Barnacle. Joyce would entertain people like Hemingway and Gertrude Stein and Picasso while Norah would be there and it made no difference to him. He was desperately in love with her. Her intelligence made no difference to him.
While he was writing Finnegan's Wake, Norah did much of the scribing for him.

It's impossible to know what he really wanted.

*** Are these stories invented or based on real life?
The Dead is materially different from most of the others. The others were snapshots of a relative few characters.
The Dead introduces you to a whole host of characters in a very social setting. The role of The Dead is not to be hypercritical of any of the characters, it's almost an act of forgiveness.

*** What does the horse represent?
Part of what he does reject in Ireland is that everything gets recycled. There are movements for Irish liberation, but they always fail. The ongoing, frustrating cycles of the lack of progress in Ireland.

*** What does Aunt Kate represent?
She may not represent any problem, but rather the stability and ongoing tradition.

*** Joyce is known for particular themes in his works. Think about how the "Dead" examines more universal themes that are not just unqiue to Ireland.
Mortality
Self-sacrifice
Love

* Wed Sep 10 10:04:32 2014
** The Curious Incident of the Dog in the Night-Time
We see that the narrator:
 - is socially awkward
 - cannot understand emotions
 - thoughts scattered
 - logical
 - honest
 - methodical
 - curious
 - selectively intelligent
 - literal
 - brave

His interpretation of reality may not be accurate.
* Thu Sep 11 13:55:32 2014
He was on a quest for truth
A kid with a disability striving to find independence
He doesn't get why people do what they do or say what they say, he is an outsider.
His brain requires him to try and impose order on a disordered world.

*** Themes
Coping with loss
Understanding the world

Themes make the story more relateable

When teenagers show independence, parents get spooked

** Tests
October 1
October 28
* Fri Sep 12 11:26:07 2014
** Poetry
*** John Donne
John Donne as a young man: a rake, a ladies man, poems about love and sex
John Donne as a priest: wrote sermons and poetry about god

*** William Blake
*** Lord Tennyson
* Mon Sep 15 14:02:16 2014
** The Book Thief
About the holocaust.
* Tue Sep 16 11:02:30 2014
** On Moral Fiction
He is railing against the kind of criticism that refers to art as a series of labels
* Tue Oct 21 08:43:26 2014
** Faustus
*** Themes
- Sin - Redemption - Damnation
- Conscience
- Man v. God
- Corruption of/by Power
- The boring nature or banality of getting everything you want
- Wisdom v. Knowledge
- Indecision
