* Thu Sep 18 09:27:51 EDT 2014
* 2014-10-08 13:14
He is allowing the evil to deceive him
Line 661
Responsible for the downfall of his wife
Tyrants think that they are always right, self-absorbed
Creon is searching for what he does not have
Coup d’etat - strike at the head
A strong leader would say “I have new evidence/advice, and I am doing something different”
Line 712
Creon is going against the will of the people
Rep the people
* 2014-10-09 08:46
The more he tries to hold on to power, the more he loses it
Creon is trying to brush this off
Antigone is going to destroy both Creon and Haemon
He refers to his fathers decisions as empty judgments
It’s just like what Laius tried to do to Oedipus
Creon understands that he cannot have blood on his hands because then the gods will go after him
Martyrs never die
She wanted her life to matter
Creon will lose at the end of the day
Homemade Sin
* Thu Oct 16 08:48:58 2014
He did not trust in the people.
Ronald Reagan's big chance in the 1984 election was "Trust in the People"
If Creon had trusted in the people, he could have it all
Death, and the living, are guilty of their deaths 
Truly his own hand? Or his father's?
She killed herself
Did Antigone know should we be freed and kill herself anyway? or did she not know and decide that it was time? If she did not know, she was exerting control over her final destiny by doing herself in before Creon's henchmen could.
Haemon realizes that he is no better than his father, using violence and fear and intimidation, so he kills himself
There is sometimes danger in too much silence
My son you were so young, so young to die.
* Thu Oct 23 08:47:17 2014
* Tue Oct 28 09:44:55 2014
** Medea
Jason wants to marry the princess to give Medea and the children more money
* Wed Oct 29 13:21:33 2014
** Medena
She gave up her entire life for Jason
* Mon Nov  3 09:22:46 2014
Pyrrhic victory
* Mon Nov 24 09:24:20 2014
lmaomaloemlcaoheilrocaheularecm;q lcmalicboircbeum oalimcroi aoeibiaeolch
oh children how lmao topkek 
