* Wed Sep  3 13:24:21 2014
** What is art?
Art, in its most basic form, is a reflection of life. In many ways, literature is a written form of art.

** What do we mean by classical literature?
Classical literature means a piece of literature which is as relevant today as it was when it was written.
Can you understand what's happening to the character of Oedipus Rex?
Can you undestand the message of Sophocles?

We are starting out with Oedipus Rex because many scholars state the it is the most important play written in any culture.
Ultimately, Oedipus Rex is us. He has to seek redemption.

Why are some people afraid to fly? Because they lose control. We need to realize that we can't control every situation.

Oedipus must accept responsibility for himself. One of the hardest things he has to day is forgive himself.

The story of Oedipus Rex was already known to everyone for generations before Sophocles was even born.
The reason he wrote the play was to examine the existential questions we all have.

Joseph Campbell wrote a book called "The Power of Myth" about the power of mythology.
He says it was a society's way of telling the future that they were here.

** What is the play about?
The play is about Oedipus discovering his own struggles.
When the play opens, it is in the past. It is a discovery of the truth, and his choice of life or death. 

* Thu Sep  4 08:33:37 2014
** The Facts of the Story
When you went to see this play, you already knew what was going to happen.
The play takes place in the past.
It opens up in pursuit of the truth, aka in medias res.

There is a city called Thebes, and ancient Thebes is located in Egypt.
There is a king called Laius. His wife is Iocosta. 
There is a prophecy. Many scholars believe that it is a little older than the Trojan War. The prophet goes to Laius and tells him that he will have a son, and that the son will grow up to kill you. He tells no one.
Iocosta becomes pregnant, and she gives birth to a baby boy. Laius is freaking out, so he tells the servant to take the infant child, to tell Iocosta that the child died, and pierce holes in the foot and ankle area of the baby, and to kill the baby.
He tells the servant to leave the baby on a mountain.

In the ancient world, if you murdered a family memeber, you had blood guilt on your hands.

The servant doesn't have it in him to murder the child. The servant gives the baby to someone in Corinth, which is basically the Las Vegas of its day. Laius's servant gives the baby to another servant, the servant to the King and Queen of Corinth.

Oedipus means "Swolen foot".

The king and queen raise Oedipus of their own child.

Oedipus grows up, and he turns 18. In vino veritas. Oedipus hears a rumour that he was destined to murder his father, marry his mother, and have children with his mother. Oedipus is sickened by this, and begins his self-destructive behaviour.
He decides the only way to avoid the prophecy was to leave. What Oedipus doesn't realize is that the more he tries to run away, the more he runs towards it. Ultimately, Oedipus has to live through his destiny. He cannot find peace until he faces the darkness.
Oedipus heads in the direction of Thebes. He sees a city called Thebes. There's a problem. Right outside of Thebes, he encounters a creature, the sphinx. The sphinx will not let him through unless he answers a riddle. The riddle is "what walks on four legs in the morning, two legs in the afternoon, and three legs in the evening." Oedipus solves the riddle and the sphinx self-destructs. 

Oedipus goes into Thebes and he finds out that the people have been suffering, and they welcome him as a hero because he destroyed the sphinx

On the road to Thebes, Oedipus's cart has an accident with a group of men where their carts collide at a fork in the road. Oedipus becomes very angry and loses his temper. He starts arguing, and then punches one of them. The guy falls and hits his head on a rock and dies. Oedipus does not know the man is dead. 
The man was his dad. His dad dies. Of course, the other men were his entourage.

One of the main questions regarding the play is the question of destiny. To the ancient Greeks, this concept of destiny/fate cannot be avoided. That Greek word is hamartia, "fatal flaw", and Oedipus's fatal flaw was hubris.
The roman's were control freaks, and they had a different concept of fate. They said there's destiny and fate, but you have input into what happens.
Fate vs. Free Will is one of the questions that people ask about the play.

* Fri Sep  5 13:11:45 2014
Dude sends one of the guys to the Oracle of Apollo, who responded that the plague was a punishment from the gods, because the murderer of Laius was never brought to justice.
Therasius comes in.

** Book Notes
Children: Future, truth and innocence, redemption

Can Oedipus save himself?

The purpose of the chorus was sometimes to be the conscious of the characters in the play. Sometimes, it was the voice of the author of the play. Sometimes, it was communicating events or information. Sometimes, it was the conscience of the audience.


Strophy: hope, immortal, healer

* Mon Sep  8 09:21:33 2014
Oedipus tries to turn something bad into something good.
Teirasias is physically blind, but he sees the truth. Oedipus is not blind, but does not see the truth
The conversation between Oedipus and the Chorus only took place in his mind.
He comes to terms with the hand that fate has dealt him.
He doesn't know if he wants to live. 
Thebes.
* Tue Sep  9 09:23:55 2014
Oedipus is trying to avoid hurting others and trying to avoid hurting himself.
Oedipus blinds himself, because then, that is his way of saying "I was blind but now I see"
We're not in control.
Oedipus cannot come to terms with the truth.
You have your eyes but blah blah.
Reference to his exile
He must die to his own sin, he must die to his past.
You are the murderer of Laius 
* Thu Sep 11 08:34:14 2014
* Fri Sep 12 13:21:09 2014
* Mon Sep 15 09:19:48 2014
