* Introduction
	This is my Emacs configuration. The main features are:
	- Evil
	- More ergonomic binds for Dvorak
  - [[https://github.com/zovt/emacs-simple-theme][My own theme]]

* Configuration
** Basics
*** Visual
		Basic visual changes, mostly disabling the UI
#+BEGIN_SRC emacs-lisp :tangle yes
(setq-default initial-scratch-message "")
(setq-default inhibit-startup-message t)
(setq-default visible-bell t)
(tool-bar-mode 0)
(menu-bar-mode 0)
(scroll-bar-mode 0)
(blink-cursor-mode 0)
(setq-default truncate-lines t)
#+END_SRC

*** Font
#+BEGIN_SRC emacs-lisp :tangle yes
(set-face-font 'default "Fantasque Sans Mono-16")
(global-prettify-symbols-mode)
#+END_SRC

*** Custom file
#+BEGIN_SRC emacs-lisp :tangle yes
(setq-default custom-file "~/.emacs.d/custom.el")
(load custom-file 'noerror)
#+END_SRC

*** Backups
#+BEGIN_SRC emacs-lisp :tangle yes
(setq-default backup-directory-alist '(("" . "~/.emacs.d/backups")))
#+END_SRC

*** Start server
#+BEGIN_SRC emacs-lisp :tangle yes
(add-hook 'after-init-hook 'server-start)
#+END_SRC

*** Confirm kill emacs
#+BEGIN_SRC emacs-lisp :tangle yes
(setq-default confirm-kill-emacs 'yes-or-no-p)
#+END_SRC

*** repeat mark command pop
		This makes the mark popping command repeat when hit multiple times in
		succession
#+BEGIN_SRC emacs-lisp :tangle yes
(setq-default set-mark-command-repeat-pop t)
#+END_SRC

** Packaging
#+BEGIN_SRC emacs-lisp :tangle yes
(require 'package)
#+END_SRC

*** Repositories
		These contain the packages that I install later.
#+BEGIN_SRC emacs-lisp :tangle yes
(add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
(add-to-list 'package-archives '("marmalade" . "https://marmalade-repo.org/packages/") t)

(package-initialize)
#+END_SRC

*** use-package
		I use use-package to install and configure my packages. This checks if
		use-package is installed and if not, installs it.
#+BEGIN_SRC emacs-lisp :tangle yes
(if (not (package-installed-p 'use-package))
    (progn (package-refresh-contents) (package-install 'use-package)))
#+END_SRC

*** Vendoring
		This allows me to load code which is not on any of the package repositories
		in Emacs-Lisp
#+BEGIN_SRC emacs-lisp :tangle yes
(setq-default vendor-dir "~/.emacs.d/vendor")
(defun vendor-and-load-remote-file (remote local-name)
  "Automatically save REMOTE to LOCAL-NAME under `vendor-dir'."
  (if (not (file-exists-p vendor-dir))
      (make-directory vendor-dir))
  (let ((local-file (expand-file-name local-name vendor-dir)))
    (if (not (file-exists-p local-file))
        (url-copy-file remote local-file))
    (load-file local-file)))
#+END_SRC

** Theme
#+BEGIN_SRC emacs-lisp :tangle yes
;; (use-package challenger-deep-theme :ensure t :init (load-theme 'challenger-deep t))
;; (use-package espresso-theme :ensure t :init (load-theme 'espresso t))
;; (use-package plan9-theme :ensure t :init (load-theme 'plan9 t))
;; (use-package color-theme-solarized :ensure t
;;   :init (load-theme 'solarized t)
;;   :config (setq-default frame-background-mode 'light))
(vendor-and-load-remote-file "https://raw.githubusercontent.com/zovt/emacs-simple-theme/master/simple-theme.el" "simple-theme.el")
(enable-theme 'simple)
#+END_SRC

** Packages and Modes
	 This is where most of the magic happens. Here I load various packages and
	 modes and configure them.

*** auto-fill-mode for comments
#+BEGIN_SRC emacs-lisp :tangle yes
(add-hook 'prog-mode-hook (lambda ()
                            (interactive)
                            (auto-fill-mode 1)
                            (setq comment-auto-fill-only-comments t)))
#+END_SRC

*** whitespace-mode
#+BEGIN_SRC emacs-lisp :tangle yes
(require 'whitespace)
(setq-default whitespace-line-column 80
              whitespace-style '(face lines-tail))
(global-whitespace-mode 1)
#+END_SRC

*** electric-pair-mode
#+BEGIN_SRC emacs-lisp :tangle yes
(electric-pair-mode)
#+END_SRC

*** undo-tree
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package undo-tree :ensure t)
#+END_SRC

*** company
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package company :ensure t
  :config
  (setq-default company-idle-delay 0.3)
  (setq-default company-minimum-prefix-length 4)
  (define-key company-active-map (kbd "C-w") 'kill-region-or-backward-kill-word)
  (add-hook 'after-init-hook 'global-company-mode))
#+END_SRC

*** flycheck
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package flycheck :ensure t :init (global-flycheck-mode))
#+END_SRC

*** smart-tabs
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package smart-tabs-mode :ensure t :config (smart-tabs-insinuate 'c 'c++ 'javascript))
#+END_SRC

*** smooth scrolling
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package smooth-scrolling :ensure t :config (smooth-scrolling-mode 1))
#+END_SRC

*** ivy
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ivy :ensure t :init (ivy-mode)
  :config
  (setq-default ivy-use-virtual-buffers t
                ivy-count-format "%d/%d"))
#+END_SRC

*** swiper
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package swiper :ensure t)
#+END_SRC

*** counsel
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package counsel :ensure t)
#+END_SRC

*** ripgrep
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ripgrep :ensure t)
#+END_SRC

*** magit
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package magit :ensure t)
#+END_SRC

*** rest client
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package restclient :ensure t)
#+END_SRC

*** diff-hl
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package diff-hl :ensure t
  :config
  (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)
  (global-diff-hl-mode))
#+END_SRC

*** rainbow-delimiters
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package rainbow-delimiters :ensure t
  :config
  (add-hook 'emacs-lisp-mode-hook 'rainbow-delimiters-mode))
#+END_SRC

*** Multiple cursors
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package multiple-cursors :ensure t
  :config
  (global-set-key (kbd "C-S-t") 'mc/mark-next-like-this-symbol)
  (global-set-key (kbd "C-<") 'mc/mark-all-symbols-like-this))
#+END_SRC

*** Evil
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package evil :ensure t
  :config
	(evil-mode 1)
  (evil-global-set-key 'normal (kbd "<SPC>") (lambda () (interactive) (setq unread-command-events (listify-key-sequence "\C-c")))))
#+END_SRC

**** Evil-magit
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package evil-magit :ensure t)
#+END_SRC

*** nlinum-relative
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package nlinum-relative :ensure t
  :config
  (nlinum-relative-setup-evil)
  (add-hook 'prog-mode-hook 'nlinum-relative-mode))
#+END_SRC

*** org mode
#+BEGIN_SRC emacs-lisp :tangle yes
(require 'org nil t)
(add-hook 'org-mode-hook (lambda ()
                           (auto-fill-mode)
                           (setq-local fill-column 80)))
(setq-default org-todo-keywords '((sequence
                                   "TODO(t!)"
                                   "IN-PROGRESS(i!)"
                                   "BLOCKED(b@)"
                                   "REVIEW(r@)"
                                   "DONE(d!)"
                                   "CANCELED(c@)"
                                   )))
(bind-key (kbd "C-c C-,") 'org-todo org-mode-map)
#+END_SRC

*** exec path from shell
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package exec-path-from-shell :ensure t :init (when (memq window-system '(mac ns x)) (exec-path-from-shell-initialize)))
#+END_SRC

*** ledger
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ledger-mode :ensure t
  :config
  (setq-default ledger-mode-should-check-version nil
                ledger-report-links-in-register nil
                ledger-binary-path "hledger"))
#+END_SRC

*** ace-window
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ace-window :ensure t :config (setq-default aw-dispatch-always t))
#+END_SRC

*** which-key
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package which-key :ensure t :config (which-key-mode))
#+END_SRC

*** neotree
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package neotree :ensure t
  :config
  (setq neo-theme 'icons)
  (evil-global-set-key 'normal (kbd "C-c n") 'neotree-toggle)
  (evil-define-key 'normal neotree-mode-map (kbd "TAB") 'neotree-enter)
  (evil-define-key 'normal neotree-mode-map (kbd "q") 'neotree-hide)
  (evil-define-key 'normal neotree-mode-map (kbd "RET") 'neotree-enter))
#+END_SRC

*** all-the-icons
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package all-the-icons :ensure t
  :config
  (setq all-the-icons-color-icons nil))
#+END_SRC

**** all-the-icons-dired
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package all-the-icons-dired :ensure t
  :config
  (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))
#+END_SRC

*** Programming languages
		This is where all of my programming-language-specific configuration lives

**** Lisp and Emacs-Lisp
#+BEGIN_SRC emacs-lisp :tangle yes
(defun disable-tabs () "Disable tabs locally in a buffer." (setq-local indent-tabs-mode nil))
(add-hook 'lisp-mode-hook 'disable-tabs)
(add-hook 'emacs-lisp-mode-hook 'disable-tabs)
#+END_SRC

**** Go
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package go-mode :ensure t
  :config
  (setq-default gofmt-command "goimports")
  (add-hook 'go-mode-hook (lambda ()
                            (add-hook 'before-save-hook 'gofmt-before-save)
                            (subword-mode 1)
                            (setq-local compile-command "noti go test")))
  (define-key go-mode-map (kbd "C-c g d") 'godef-jump)
  (define-key go-mode-map (kbd "C-c g D") 'godef-jump-other-window)
  (define-key go-mode-map (kbd "C-c C")
    (lambda () (interactive)
      (start-process-shell-command "*go integration test*" "*go integration test*"
                                   (concat "cd " (locate-dominating-file default-directory ".git") " && noti make integration-test;"))
      (with-current-buffer "*go integration test*"
        (local-set-key (kbd "C-c C-c") (lambda () (interactive)
                                         (delete-process "*go integration test*")
                                         (kill-buffer "*go integration test*"))))
      (switch-to-buffer-other-window "*go integration test*"))))
(use-package company-go :ensure t :config (add-to-list 'company-backends 'company-go))
#+END_SRC

**** Rust
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package flycheck-rust :ensure t
  :config
  (add-hook 'flycheck-mode-hook 'flycheck-rust-setup))
(use-package racer :ensure t)
(use-package rust-mode :ensure t
  :config
  (add-hook 'rust-mode-hook 'racer-mode)
  (add-hook 'racer-mode-hook 'eldoc-mode)
  (add-hook 'rust-mode-hook (lambda ()
                              (setq-local indent-tabs-mode t)
                              (setq-local tab-width 2)
                              (setq-local rust-indent-offset 2)))
  (setq-default rust-format-on-save t)
	(define-key racer-mode-map (kbd "C-c t d") 'racer-find-definition)
	(define-key racer-mode-map (kbd "C-c t D") 'racer-describe))
#+END_SRC

**** Prose (the written word)
#+BEGIN_SRC emacs-lisp :tangle yes
(vendor-and-load-remote-file "https://raw.githubusercontent.com/amperser/proselint/master/plugins/flycheck/flycheck-proselint.el"
                             "flycheck-proselint.el")

(vendor-and-load-remote-file "https://raw.githubusercontent.com/abingham/flycheck-vale/master/flycheck-vale.el"
                             "flycheck-vale.el")
(add-to-list 'flycheck-checkers 'vale)
#+END_SRC

*** Code Visuals
#+BEGIN_SRC emacs-lisp :tangle yes
(setq-default tab-width 2)
(add-hook 'prog-mode-hook 'show-paren-mode)
#+END_SRC

** Useful Functions
#+BEGIN_SRC emacs-lisp :tangle yes
;; editing
(defun scratch () "Create a new scratch buffer."
       (interactive)
       (switch-to-buffer "*scratch*")
       (lisp-interaction-mode))

(defun kill-region-or-backward-kill-word (&optional arg region)
  "`kill-region' if the region is active, otherwise `backward-kill-word'."
  (interactive (list (prefix-numeric-value current-prefix-arg) (use-region-p)))
  (if region (kill-region (region-beginning) (region-end))
    (backward-kill-word arg)))
#+END_SRC

** Global Keybinds
*** Quit
#+BEGIN_SRC emacs-lisp :tangle yes
(global-set-key (kbd "C-c q") 'save-buffers-kill-emacs)
#+END_SRC

*** M-x replacement
#+BEGIN_SRC emacs-lisp :tangle yes
(global-set-key (kbd "C-c x") 'counsel-M-x)
(global-set-key (kbd "M-x") 'counsel-M-x)
#+END_SRC

*** Window management
#+BEGIN_SRC emacs-lisp :tangle yes
(global-set-key (kbd "C-c w o") 'ace-window)
(global-set-key (kbd "C-c w F") 'make-frame)
(global-set-key (kbd "C-c w x") 'delete-frame)
(global-set-key (kbd "C-c w f") 'other-frame)
#+END_SRC

*** File Finding
#+BEGIN_SRC emacs-lisp :tangle yes
(global-set-key (kbd "C-c f f") 'counsel-find-file)
(global-set-key (kbd "C-c f g") 'counsel-git)
#+END_SRC

*** Swiper
#+BEGIN_SRC emacs-lisp :tangle yes
(global-set-key (kbd "C-c C-c") 'swiper)
#+END_SRC

*** Ripgrep
#+BEGIN_SRC emacs-lisp :tangle yes
(global-set-key (kbd "C-c r") 'counsel-rg)
(global-set-key (kbd "C-c R") 'ripgrep-regexp)
#+END_SRC

*** Magit
#+BEGIN_SRC emacs-lisp :tangle yes
(global-set-key (kbd "C-c G") 'magit-status)
#+END_SRC

*** Compile
#+BEGIN_SRC emacs-lisp :tangle yes
(global-set-key (kbd "C-c c") 'compile)
#+END_SRC

*** undo-tree
#+BEGIN_SRC emacs-lisp :tangle yes
(evil-global-set-key 'normal (kbd "U") 'undo-tree-visualize)
#+END_SRC

*** Buffers
#+BEGIN_SRC emacs-lisp :tangle yes
(global-set-key (kbd "C-c b b") 'ivy-switch-buffer)
(global-set-key (kbd "C-c b k") 'kill-buffer)
#+END_SRC

*** Editing
#+BEGIN_SRC emacs-lisp :tangle yes
(global-set-key (kbd "C-S-k") 'kill-whole-line)
(global-set-key (kbd "C-w") 'kill-region-or-backward-kill-word)
#+END_SRC

**** Nicer Ergonomics
		 These keys are easier to hit on Dvorak
#+BEGIN_SRC emacs-lisp :tangle yes
(define-key key-translation-map (kbd "C-h") (kbd "<DEL>"))
(define-key key-translation-map (kbd "C-'") (kbd "C-c"))
(define-key key-translation-map (kbd "C-t") (kbd "C-x"))

(global-set-key (kbd "C-c h") 'help)
(global-set-key (kbd "M-g") 'goto-line)
(global-set-key (kbd "C-;") 'save-buffer)
(global-set-key (kbd "C-,") 'transpose-chars)
#+END_SRC

** Load Local Customizations
	 This is used to load custimizations that I don't want to track in git.
#+BEGIN_SRC emacs-lisp :tangle yes
(if (file-exists-p "~/.emacs.d/local.el") (load-file "~/.emacs.d/local.el"))
#+END_SRC

* The End
#+BEGIN_SRC emacs-lisp :tangle yes
(provide 'init)
;;; init.el ends here
#+END_SRC
